# Performance de l'OCR

In [1]:
import pandas as pd
import contextlib
import pickle
import polars as pl

In [2]:
with open("csv1988.pkl","rb") as f:
    csv1988 = pl.from_pandas(pickle.load(f))

In [3]:
csv1988

shape: (3_540, 44)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ date      ┆ subject   ┆ title     ┆ … ┆ suppleant ┆ suppleant ┆ transcrip ┆ transcri │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ -liste    ┆ -decorati ┆ t         ┆ pt_lengt │
│ str       ┆ datetime[ ┆ str       ┆ str       ┆   ┆ ---       ┆ ons       ┆ ---       ┆ h        │
│           ┆ μs]       ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ EL174_L_1 ┆ 1988-06-0 ┆ France;As ┆ Élections ┆ … ┆ Liste     ┆ non       ┆ Élections ┆ 3090.0   │
│ 988_06_00 ┆ 5         ┆ semblée   ┆ législati ┆   ┆ d'entente ┆           ┆ Législati ┆          │
│ 1_01_1_PF ┆ 00:00:00  ┆ Nationale ┆ ves de    ┆   ┆ populaire ┆           ┆ ves du 5  ┆          │
│ _01       ┆           ┆ ;Ve …     ┆ 1988…     ┆   ┆ et n…     ┆           ┆ Ju…       ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Élections ┆ Élections ┆ … ┆ Une       ┆ non       ┆ RÉPUBLIQU ┆ 3602.0   │
│ 988_06_00 ┆ 5         ┆ législati ┆ législati ┆   ┆ nouvelle  ┆           ┆ E         ┆          │
│ 1_01_1_PF ┆ 00:00:00  ┆ ves;Assem ┆ ves de    ┆   ┆ politique ┆           ┆ FRANÇAISE ┆          │
│ _02       ┆           ┆ bl…       ┆ 1988…     ┆   ┆ à gauch…  ┆           ┆ -         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Liberté…  ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Assemblée ┆ Élections ┆ … ┆ Union du  ┆ oui       ┆ Sciences  ┆ 5007.0   │
│ 988_06_00 ┆ 5         ┆ Nationale ┆ législati ┆   ┆ rassemble ┆           ┆ Po /      ┆          │
│ 1_01_1_PF ┆ 00:00:00  ┆ ;Ve       ┆ ves de    ┆   ┆ ment et   ┆           ┆ fonds     ┆          │
│ _03       ┆           ┆ Républi…  ┆ 1988…     ┆   ┆ du c…     ┆           ┆ CEVIPOF   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ EL…       ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Assemblée ┆ Élections ┆ … ┆ Bresse    ┆ non       ┆ Sciences  ┆ 1664.0   │
│ 988_06_00 ┆ 5         ┆ Nationale ┆ législati ┆   ┆ unie      ┆           ┆ Po /      ┆          │
│ 1_01_1_PF ┆ 00:00:00  ┆ ;Ve       ┆ ves de    ┆   ┆ majorité  ┆           ┆ fonds     ┆          │
│ _04       ┆           ┆ Républi…  ┆ 1988…     ┆   ┆ président ┆           ┆ CEVIPOF   ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆ RÉ…       ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Ve Républ ┆ Élections ┆ … ┆ Rassemble ┆ non       ┆ RÉPUBLIQU ┆ 4225.0   │
│ 988_06_00 ┆ 5         ┆ ique;Élec ┆ législati ┆   ┆ ment des  ┆           ┆ E         ┆          │
│ 1_01_1_PF ┆ 00:00:00  ┆ tions     ┆ ves de    ┆   ┆ forces de ┆           ┆ FRANÇAISE ┆          │
│ _05       ┆           ┆ législ…   ┆ 1988…     ┆   ┆ ga…       ┆           ┆ -         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ LIBERTÉ…  ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ EL177_L_1 ┆ 1988-06-1 ┆ Assemblée ┆ Élections ┆ … ┆ Majorité  ┆ non       ┆ Claude    ┆ 3940.0   │
│ 988_06_97 ┆ 2         ┆ Nationale ┆ législati ┆   ┆ président ┆           ┆ HOARAU    ┆          │
│ 4_03_2_PF ┆ 00:00:00  ┆ ;Élection ┆ ves de    ┆   ┆ ielle     ┆           ┆ Égalité   ┆          │
│ _02       ┆           ┆ s …       ┆ 1988…     ┆   ┆           ┆           ┆ Responsa… ┆          │
│ EL177_L_1 ┆ 1988-06-1 ┆ Ve Républ ┆ Élections ┆ … ┆ non       ┆ non       ┆ Sciences  ┆ 2040.0   │
│ 988_06_97 ┆ 2         ┆ ique;Élec ┆ législati ┆   ┆ mentionné ┆           ┆ Po /      ┆          │
│ 4_04_2_PF ┆ 00:00:00  ┆ tions     ┆ ves de    ┆   ┆           ┆           ┆ fonds     ┆          │
│ _01       ┆           ┆ législ…   ┆ 1988…     ┆   ┆           ┆           ┆ CEVIPOF   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ An…       ┆          │
│ EL177_L_1 ┆ 1988-06-1 ┆ Ve Républ ┆ Élections ┆ … ┆ Majorité  ┆ non       ┆ Élie      ┆ 3927.0   │
│ 988_06_97 ┆ 2         ┆ ique;Élec ┆ législati ┆   ┆ président ┆           ┆ HOARAU    ┆          │
│ 4_04_2_PF ┆ 00:00:00  ┆ tions     ┆ ves de    ┆   ┆ ielle     ┆           ┆ Égalité   ┆          │
│ _02       ┆           ┆ législ…   ┆ 1988…     ┆   ┆           ┆           ┆ Responsab ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ i…        ┆          │
│ EL177_L_1 ┆ 1988-06-1 ┆ France;Ve ┆ Élections ┆ … ┆ Union du  ┆ non       ┆ Sciences  ┆ 1499.0   │
│ 988_06_97 ┆ 2         ┆ Républiqu ┆ législati ┆   ┆ rassemble ┆           ┆ Po /      ┆          │
│ 4_05_2_PF ┆ 00:00:00  ┆ e;Assembl ┆ ves de    ┆   ┆ ment et   ┆           ┆ fonds     ┆          │
│ _01       ┆           ┆ ée…       ┆ 1988…     ┆   ┆ du c…     ┆           ┆ CEVIPOF   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ EL…       ┆          │
│ EL177_L_1 ┆ 1988-06-1 ┆ Assemblée ┆ Élections ┆ … ┆ Majorité  ┆ non       ┆ Sciences  ┆ 3978.0   │
│ 988_06_97 ┆ 2         ┆ Nationale ┆ législati ┆   ┆ président ┆           ┆ Po /      ┆          │
│ 4_05_2_PF ┆ 00:00:00  ┆ ;Élection ┆ ves de    ┆   ┆ ielle     ┆           ┆ fonds     ┆          │
│ _02       ┆           ┆ s …       ┆ 1988…     ┆   ┆           ┆           ┆ CEVIPOF   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Pa…       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
csv1988.columns

['id',
 'date',
 'subject',
 'title',
 'contexte-election',
 'contexte-tour',
 'cote',
 'departement',
 'departement-nom',
 'departement-insee',
 'identifiant de circonscription',
 'images',
 'pdf',
 'ocr_url',
 'titulaire-nom',
 'titulaire-prenom',
 'titulaire-sexe',
 'titulaire-age',
 'titulaire-age-calcule',
 'titulaire-age-tranche',
 'titulaire-profession',
 'titulaire-mandat-en-cours',
 'titulaire-mandat-passe',
 'titulaire-associations',
 'titulaire-autres-statuts',
 'titulaire-soutien',
 'titulaire-liste',
 'titulaire-decorations',
 'suppleant-nom',
 'suppleant-prenom',
 'suppleant-sexe',
 'suppleant-age',
 'suppleant-age-calcule',
 'suppleant-age-tranche',
 'suppleant-profession',
 'suppleant-mandat-en-cours',
 'suppleant-mandat-passe',
 'suppleant-associations',
 'suppleant-autres-statuts',
 'suppleant-soutien',
 'suppleant-liste',
 'suppleant-decorations',
 'transcript',
 'transcript_length']

# Construction d'un nom normalisé / le nom figure-t-il dans le transcript ?

## Lowercase

In [25]:
df = csv1988.select(pl.col("titulaire-nom"),pl.col("transcript"), 
                    pl.col("titulaire-nom").str.to_lowercase().alias("titulaire-lowercase"),
                    pl.col("transcript").str.to_lowercase().str.contains(pl.col("titulaire-nom").str.to_lowercase()).alias("titulaire-lowercase-is-in-transcript"))

In [26]:
df.get_column("titulaire-lowercase-is-in-transcript").value_counts()

shape: (3, 2)
┌──────────────────────────────────────┬───────┐
│ titulaire-lowercase-is-in-transcript ┆ count │
│ ---                                  ┆ ---   │
│ bool                                 ┆ u32   │
╞══════════════════════════════════════╪═══════╡
│ false                                ┆ 209   │
│ true                                 ┆ 3330  │
│ null                                 ┆ 1     │
└──────────────────────────────────────┴───────┘

In [27]:
df.filter(pl.col("titulaire-lowercase-is-in-transcript") != True).select(pl.col("titulaire-lowercase"),pl.col("transcript"))

shape: (209, 2)
┌─────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ titulaire-lowercase ┆ transcript                                                                                                                                                                                                                                                                                                                                                                                                                 │
│ ---                 ┆ ---                                                                                                                                                                                                                                                                                                                                                                                                                        │
│ str                 ┆ str                                                                                                                                                                                                                                                                                                                                                                                                                        │
╞═════════════════════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ chevalier           ┆ ELECTIONS LEGISLATIVES DU 5 JUIN 1988                                                                                                                                                                                                                                                                                                                                                                                      │
│                     ┆ Les                                                                                                                                                                                                                                                                                                                                                                                                                        │
│                     ┆ A                                                                                                                                                                                                                                                                                                                                                                                                                          │
│                     ┆ HAUTES                                                                                                                                                                                                                                                                                                                                                                                                                     │
│                     ┆ LPES                                                                                                                                                                                                                                                                                                                                                                                                                       │
│                     ┆ ont du cœur                                                                                                                                                                                                                                                                                                                                                                                                                │
│                     ┆ D. CHEVALLIER Suppléant : G. GRAGLIA                                                                                                                                                                                                                                                                                                                                                                                       │
│                     ┆ MAJORITÉ PRÉSIDENTIELLE POUR UNE FRANCE UNIE                                                                                                                                                                                                                                                                                                                                                                               │
│                     ┆ Sciences Po / fonds CEVIPOFMadame, Mademoiselle, Mairieur Chers amis haut-alpins                                                                                                                                                                                                                                                                                                                                           │
│                     ┆ Plus de 51,8% d'entre vous out accordé, dans la première circonscription, leurs suffrages à François Mitterrand. Vous avez ainsi manifesté, avec moi, votre attachement à un programme de rassemblement, de tolérance et de solidarité pour une France Unie.                                                                                                                                                               │
│                     ┆ Je suis sûr que vous serez plus nombreux en use à soutenir l'action du gouvernement de Michel Rocard.                                                                                                                                                                                                                                                                                                                      │
│                     ┆ Durant ces dernières années, je suis allé le plus suivent possible à votre rencontre pour vous écouter et uns présenter les projets que j'avais à cœur de réaliser. Ce dialogue qui fait trop souvent défaut dans notre département me paraît une garantie d'efficacité.                                                                                                                                                   │
│                     ┆ Chers amis haut alpins, notre avenir tient autant dans les hommes que dans les projets Pouvons ensemble que les Hautes Alpes ont du cœur". "                                                                                                                                                                                                                                                                               │
│                     ┆ Bien sin…                                                                                                                                                                                                                                                                                                                                                                                                                  │
│ léonetti            ┆ ELECTIONS LEGISLATIVES DES 5 ET 12 JUIN 1988                                                                                                                                                                                                                                                                                                                                                                               │
│                     ┆ MAJORITE PRESIDENTIELLE POUR LA GAUCHE UNIE                                                                                                                                                                                                                                                                                                                                                                                │
│                     ┆ Antoine LEONETTI Ingénieur d'études à l'Université de Nice                                                                                                                                                                                                                                                                                                                                                                 │
│                     ┆ Georges COURBOULEX Conseiller Municipal de la Trinité Suppléant                                                                                                                                                                                                                                                                                                                                                            │
│                     ┆ Pour construire il faut savoir se servir de ses deux mains, mais nous savons encore distinguer notre main droite de notre main gauche .                                                                                                                                                                                                                                                                                    │
│                     ┆ Sciences Po / fonds CEVIPOFCitoyennes, Citoyens,                                                                                                                                                                                                                                                                                                                                                                           │
│                     ┆ La France, en rélisant à la Présidence de la République François Mitterrand a choisi la voie de l'union et du Progrès.                                                                                                                                                                                                                                                                                                     │
│                     ┆ Georges Courboule+ et moi-même, nous avons participé à cette victoire, comme beaucoup d'entre vous .                                                                                                                                                                                                                                                                                                                       │
│                     ┆ L'union est une nécessité pour la France, pour l'Europe, pour la Démocratie. Nul si'a le monopole du patriotisme.                                                                                                                                                                                                                                                                                                          │
│                     ┆ Cependant, la République mérite mieux qu'un rassemblement de circonstance sur un programme péou.                                                                                                                                                                                                                                                                                                                           │
│                     ┆ Je ne doute à aucun moment de la volonté de F. Mitterrand de rassembler la France plutôt que de la diviser par l'intolérance, l'injustice et l'exclusion des plus faibles .                                                                                                                                                                                                                                                │
│                     ┆ …                                                                                                                                                                                                                                                                                                                                                                                                                          │
│ vassalo             ┆ DÉPARTEMENT DES ALPES-MARITIMES                                                                                                                                                                                                                                                                                                                                                                                            │
│                     ┆ RÉPUBLIQUE FRANÇAISE                                                                                                                                                                                                                                                                                                                                                                                                       │
│                     ┆ ÉLECTIONS LÉGISLATIVES JUIN 1988 9e CIRCONSCRIPTION                                                                                                                                                                                                                                                                                                                                                                        │
│                     ┆ Georges VASSALLO Principal de college - Conseiller municipal - Ancien maire de Grasse Ancien vice-président du Conseil régional de Provence-Alpes-Côte d'Azur                                                                                                                                                                                                                                                              │
│                     ┆ Suppléant : Pierre BERNASCONI Professeur (Le Cannet)                                                                                                                                                                                                                                                                                                                                                                       │
│                     ┆ CANDIDATS DE RASSEMBLEMENT DES FORCES DE GAUCHE présentés par le PARTI COMMUNISTE FRANÇAIS                                                                                                                                                                                                                                                                                                                                 │
│                     ┆ Madame, Mademoiselle, Monsieur,                                                                                                                                                                                                                                                                                                                                                                                            │
│                     ┆ Quelques semaines seulement après l'élection présidentielle, des élections auront lieu le 5 juin pour élire les députés qui pendant cinq ans voteront des lois et budgets qui auront des conséquences pour la vie de chacun.                                                                                                                                                                                               │
│                     ┆ Selon le choix que vous ferez, la situation pourra s'améliorer ou s'aggraver.                                                                                                                                                                                                                                                                                                                                              │
│                     ┆ Elle s'aggravera, bien sûr, si vous votez pour un candidat de droite ou d'extrême droite.                                                                                                                                                                                                                                                                                                                                  │
│                     ┆ On connaît la politique du R.P.R., de l'U.D.F. et du F.N. On les a vu à l'œuvre de 1986 à 1988. Avec eux, le pays a été dirigé dans l'intérêt exclusif des grands capitalist…                                                                                                                                                                                                                                              │
│ béraud              ┆ DÉPARTEMENT DE L'ARDÈCHE                                                                                                                                                                                                                                                                                                                                                                                                   │
│                     ┆ ELECTIONS LEGISLATIVES JUIN 88                                                                                                                                                                                                                                                                                                                                                                                             │
│                     ┆ RÉPUBLIQUE FRANÇAISE                                                                                                                                                                                                                                                                                                                                                                                                       │

On remarque que plus de 90% des transcripts contiennent bien le nom du titulaire. Les situations dans lesquelles le nom n'est pas retrouvé correspondent pour la plupart à des noms accentués.

## Unidecode / closest ASCII equivalent

In [ ]:
from unidecode import unidecode

# Experiments

In [16]:
toto = csv1988.select(pl.col("titulaire-nom"),pl.col("transcript"), 
               pl.col("titulaire-nom").str.to_lowercase().alias("l"),
               pl.col("transcript").str.to_lowercase().str.contains(pl.col("titulaire-nom").str.to_lowercase()).alias("res"))

In [22]:
toto.get_column("res").value_counts()

shape: (3, 2)
┌───────┬───────┐
│ res   ┆ count │
│ ---   ┆ ---   │
│ bool  ┆ u32   │
╞═══════╪═══════╡
│ true  ┆ 3330  │
│ false ┆ 209   │
│ null  ┆ 1     │
└───────┴───────┘

In [24]:
toto.filter(pl.col("res") != True)

shape: (209, 4)
┌───────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────┬───────┐
│ titulaire-nom ┆ transcript                                                                                                                                                                                                                                                                                                                                                                                                                 ┆ l            ┆ res   │
│ ---           ┆ ---                                                                                                                                                                                                                                                                                                                                                                                                                        ┆ ---          ┆ ---   │
│ str           ┆ str                                                                                                                                                                                                                                                                                                                                                                                                                        ┆ str          ┆ bool  │
╞═══════════════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════╪═══════╡
│ Chevalier     ┆ ELECTIONS LEGISLATIVES DU 5 JUIN 1988                                                                                                                                                                                                                                                                                                                                                                                      ┆ chevalier    ┆ false │
│               ┆ Les                                                                                                                                                                                                                                                                                                                                                                                                                        ┆              ┆       │
│               ┆ A                                                                                                                                                                                                                                                                                                                                                                                                                          ┆              ┆       │
│               ┆ HAUTES                                                                                                                                                                                                                                                                                                                                                                                                                     ┆              ┆       │
│               ┆ LPES                                                                                                                                                                                                                                                                                                                                                                                                                       ┆              ┆       │
│               ┆ ont du cœur                                                                                                                                                                                                                                                                                                                                                                                                                ┆              ┆       │
│               ┆ D. CHEVALLIER Suppléant : G. GRAGLIA                                                                                                                                                                                                                                                                                                                                                                                       ┆              ┆       │
│               ┆ MAJORITÉ PRÉSIDENTIELLE POUR UNE FRANCE UNIE                                                                                                                                                                                                                                                                                                                                                                               ┆              ┆       │
│               ┆ Sciences Po / fonds CEVIPOFMadame, Mademoiselle, Mairieur Chers amis haut-alpins                                                                                                                                                                                                                                                                                                                                           ┆              ┆       │
│               ┆ Plus de 51,8% d'entre vous out accordé, dans la première circonscription, leurs suffrages à François Mitterrand. Vous avez ainsi manifesté, avec moi, votre attachement à un programme de rassemblement, de tolérance et de solidarité pour une France Unie.                                                                                                                                                               ┆              ┆       │
│               ┆ Je suis sûr que vous serez plus nombreux en use à soutenir l'action du gouvernement de Michel Rocard.                                                                                                                                                                                                                                                                                                                      ┆              ┆       │
│               ┆ Durant ces dernières années, je suis allé le plus suivent possible à votre rencontre pour vous écouter et uns présenter les projets que j'avais à cœur de réaliser. Ce dialogue qui fait trop souvent défaut dans notre département me paraît une garantie d'efficacité.                                                                                                                                                   ┆              ┆       │
│               ┆ Chers amis haut alpins, notre avenir tient autant dans les hommes que dans les projets Pouvons ensemble que les Hautes Alpes ont du cœur". "                                                                                                                                                                                                                                                                               ┆              ┆       │
│               ┆ Bien sin…                                                                                                                                                                                                                                                                                                                                                                                                                  ┆              ┆       │
│ Léonetti      ┆ ELECTIONS LEGISLATIVES DES 5 ET 12 JUIN 1988                                                                                                                                                                                                                                                                                                                                                                               ┆ léonetti     ┆ false │
│               ┆ MAJORITE PRESIDENTIELLE POUR LA GAUCHE UNIE                                                                                                                                                                                                                                                                                                                                                                                ┆              ┆       │
│               ┆ Antoine LEONETTI Ingénieur d'études à l'Université de Nice                                                                                                                                                                                                                                                                                                                                                                 ┆              ┆       │
│               ┆ Georges COURBOULEX Conseiller Municipal de la Trinité Suppléant                                                                                                                                                                                                                                                                                                                                                            ┆              ┆       │
│               ┆ Pour construire il faut savoir se servir de ses deux mains, mais nous savons encore distinguer notre main droite de notre main gauche .                                                                                                                                                                                                                                                                                    ┆              ┆       │
│               ┆ Sciences Po / fonds CEVIPOFCitoyennes, Citoyens,                                                                                                                                                                                                                                                                                                                                                                           ┆              ┆       │
│               ┆ La France, en rélisant à la Présidence de la République François Mitterrand a choisi la voie de l'union et du Progrès.                                                                                                                                                                                                                                                                                                     ┆              ┆       │
│               ┆ Georges Courboule+ et moi-même, nous avons participé à cette victoire, comme beaucoup d'entre vous .                                                                                                                                                                                                                                                                                                                       ┆              ┆       │
│               ┆ L'union est une nécessité pour la France, pour l'Europe, pour la Démocratie. Nul si'a le monopole du patriotisme.                                                                                                                                                                                                                                                                                                          ┆              ┆       │
│               ┆ Cependant, la République mérite mieux qu'un rassemblement de circonstance sur un programme péou.                                                                                                                                                                                                                                                                                                                           ┆              ┆       │
│               ┆ Je ne doute à aucun moment de la volonté de F. Mitterrand de rassembler la France plutôt que de la diviser par l'intolérance, l'injustice et l'exclusion des plus faibles .                                                                                                                                                                                                                                                ┆              ┆       │
│               ┆ …                                                                                                                                                                                                                                                                                                                                                                                                                          ┆              ┆       │
│ Vassalo       ┆ DÉPARTEMENT DES ALPES-MARITIMES                                                                                                                                                                                                                                                                                                                                                                                            ┆ vassalo      ┆ false │
│               ┆ RÉPUBLIQUE FRANÇAISE                                                                                                                                                                                                                                                                                                                                                                                                       ┆              ┆       │
│               ┆ ÉLECTIONS LÉGISLATIVES JUIN 1988 9e CIRCONSCRIPTION                                                                                                                                                                                                                                                                                                                                                                        ┆              ┆       │
│               ┆ Georges VASSALLO Principal de college - Conseiller municipal - Ancien maire de Grasse Ancien vice-président du Conseil régional de Provence-Alpes-Côte d'Azur                                                                                                                                                                                                                                                              ┆              ┆       │
│               ┆ Suppléant : Pierre BERNASCONI Professeur (Le Cannet)                                                                                                                                                                                                                                                                                                                                                                       ┆              ┆       │
│               ┆ CANDIDATS DE RASSEMBLEMENT DES FORCES DE GAUCHE présentés par le PARTI COMMUNISTE FRANÇAIS                                                                                                                                                                                                                                                                                                                                 ┆              ┆       │
│               ┆ Madame, Mademoiselle, Monsieur,                                                                                                                                                                                                                                                                                                                                                                                            ┆              ┆       │
│               ┆ Quelques semaines seulement après l'élection présidentielle, des élections auront lieu le 5 juin pour élire les députés qui pendant cinq ans voteront des lois et budgets qui auront des conséquences pour la vie de chacun.                                                                                                                                                                                               ┆              ┆       │
│               ┆ Selon le choix que vous ferez, la situation pourra s'améliorer ou s'aggraver.                                                                                                                                                                                                                                                                                                                                              ┆              ┆       │
│               ┆ Elle s'aggravera, bien sûr, si vous votez pour un candidat de droite ou d'extrême droite.                                                                                                                                                                                                                                                                                                                                  ┆              ┆       │
│               ┆ On connaît la politique du R.P.R., de l'U.D.F. et du F.N. On les a vu à l'œuvre de 1986 à 1988. Avec eux, le pays a été dirigé dans l'intérêt exclusif des grands capitalist…                                                                                                                                                                                                                                              ┆              ┆       │
│ Béraud        ┆ DÉPARTEMENT DE L'ARDÈCHE                                                                                                                                                                                                                                                                                                                                                                                                   ┆ béraud       ┆ false │
│               ┆ ELECTIONS LEGISLATIVES JUIN 88                                                                                                                                                                                                                                                                                                                                                                                             ┆              ┆       │

In [6]:
# attention aux accents => string normalization

In [7]:
csv1988["transcript"].str.contains("je")

shape: (3_540,)
Series: 'transcript' [bool]
[
	false
	true
	true
	true
	true
	…
	true
	true
	true
	true
	true
]

In [8]:
extract = csv1988.head(3)

In [9]:
extract

shape: (3, 44)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ date      ┆ subject   ┆ title     ┆ … ┆ suppleant ┆ suppleant ┆ transcrip ┆ transcri │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ -liste    ┆ -decorati ┆ t         ┆ pt_lengt │
│ str       ┆ datetime[ ┆ str       ┆ str       ┆   ┆ ---       ┆ ons       ┆ ---       ┆ h        │
│           ┆ μs]       ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ EL174_L_1 ┆ 1988-06-0 ┆ France;As ┆ Élections ┆ … ┆ Liste     ┆ non       ┆ Élections ┆ 3090.0   │
│ 988_06_00 ┆ 5         ┆ semblée   ┆ législati ┆   ┆ d'entente ┆           ┆ Législati ┆          │
│ 1_01_1_PF ┆ 00:00:00  ┆ Nationale ┆ ves de    ┆   ┆ populaire ┆           ┆ ves du 5  ┆          │
│ _01       ┆           ┆ ;Ve …     ┆ 1988…     ┆   ┆ et n…     ┆           ┆ Ju…       ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Élections ┆ Élections ┆ … ┆ Une       ┆ non       ┆ RÉPUBLIQU ┆ 3602.0   │
│ 988_06_00 ┆ 5         ┆ législati ┆ législati ┆   ┆ nouvelle  ┆           ┆ E         ┆          │
│ 1_01_1_PF ┆ 00:00:00  ┆ ves;Assem ┆ ves de    ┆   ┆ politique ┆           ┆ FRANÇAISE ┆          │
│ _02       ┆           ┆ bl…       ┆ 1988…     ┆   ┆ à gauch…  ┆           ┆ -         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Liberté…  ┆          │
│ EL174_L_1 ┆ 1988-06-0 ┆ Assemblée ┆ Élections ┆ … ┆ Union du  ┆ oui       ┆ Sciences  ┆ 5007.0   │
│ 988_06_00 ┆ 5         ┆ Nationale ┆ législati ┆   ┆ rassemble ┆           ┆ Po /      ┆          │
│ 1_01_1_PF ┆ 00:00:00  ┆ ;Ve       ┆ ves de    ┆   ┆ ment et   ┆           ┆ fonds     ┆          │
│ _03       ┆           ┆ Républi…  ┆ 1988…     ┆   ┆ du c…     ┆           ┆ CEVIPOF   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ EL…       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
extract.select(pl.col("titulaire-nom"),pl.col("transcript"), 
               pl.col("titulaire-nom").str.to_lowercase().alias("l"),
               pl.col("transcript").str.to_lowercase().str.contains(pl.col("titulaire-nom").str.to_lowercase()).alias("res"))

shape: (3, 4)
┌───────────────┬─────────────────────────────────┬─────────┬──────┐
│ titulaire-nom ┆ transcript                      ┆ l       ┆ res  │
│ ---           ┆ ---                             ┆ ---     ┆ ---  │
│ str           ┆ str                             ┆ str     ┆ bool │
╞═══════════════╪═════════════════════════════════╪═════════╪══════╡
│ Aulagne       ┆ Élections Législatives du 5 Ju… ┆ aulagne ┆ true │
│ Pujol         ┆ RÉPUBLIQUE FRANÇAISE - Liberté… ┆ pujol   ┆ true │
│ Boyon         ┆ Sciences Po / fonds CEVIPOF     ┆ boyon   ┆ true │
│               ┆ EL…                             ┆         ┆      │
└───────────────┴─────────────────────────────────┴─────────┴──────┘

In [11]:
pl.Config(fmt_str_lengths=1000, tbl_width_chars=1000)

In [12]:
extract.select(pl.col("titulaire-soutien"), pl.col("titulaire-liste"))

shape: (3, 2)
┌─────────────────────────────────────────────────────────────────────┬────────────────────────────────────────┐
│ titulaire-soutien                                                   ┆ titulaire-liste                        │
│ ---                                                                 ┆ ---                                    │
│ str                                                                 ┆ str                                    │
╞═════════════════════════════════════════════════════════════════════╪════════════════════════════════════════╡
│ Front national                                                      ┆ Liste d'entente populaire et nationale │
│ Comités Juquin                                                      ┆ Une nouvelle politique à gauche        │
│ Rassemblement pour la République;Union pour la démocratie française ┆ Union du rassemblement et du centre    │
└─────────────────────────────────────────────────────────────────────┴────────────────────────────────────────┘

In [13]:
csv1988.select(pl.col("titulaire-soutien").value_counts()).unnest("titulaire-soutien")

shape: (157, 2)
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────┐
│ titulaire-soutien                                                                                                                           ┆ count │
│ ---                                                                                                                                         ┆ ---   │
│ str                                                                                                                                         ┆ u32   │
╞═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═══════╡
│ Union pour la démocratie française;Centre des démocrates sociaux                                                                            ┆ 11    │
│ divers droite;Racines du futur                                                                                                              ┆ 1     │
│ Jura écologie                                                                                                                               ┆ 2     │
│ Union centriste républicaine                                                                                                                ┆ 2     │
│ Parti socialiste                                                                                                                            ┆ 179   │
│ …                                                                                                                                           ┆ …     │
│ centre gauche                                                                                                                               ┆ 1     │
│ non inscrit;sans étiquette                                                                                                                  ┆ 1     │
│ Rassemblement pour la République;Union pour la démocratie française;Centre national des indépendants et paysans;Comité central bonapartiste ┆ 2     │
│ socialistes                                                                                                                                 ┆ 1     │
│ non inscrit                                                                                                                                 ┆ 1     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────┘

In [14]:
extract.select(pl.col("transcript"))

shape: (3, 1)
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ transcript                                                                                                                                                                                                                                                                                                                        │
│ ---                                                                                                                                                                                                                                                                                                                               │
│ str                                                                                                                                                                                                                                                                                                                               │
╞═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ Élections Législatives du 5 Juin 1988 - Département de l'Ain - 1re circonscription                                                                                                                                                                                                                                                │
│ Sciences Po / fonds CEVIPOF                                                                                                                                                                                                                                                                                                       │
│ Maintenant la force d'avenir c'est le Front National                                                                                                                                                                                                                                                                              │
│ Appel aux Français,                                                                                                                                                                                                                                                                                                               │
│ Le 24 Avril, 4.400.000 électrices et électeurs m'ont fait confiance : - pour promouvoir le programme de redressement national, - pour réduire le chômage, l'immigration, l'insécurité, - pour lutter contre le socialisme bureaucratique et fiscaliste. Je leur demande de confirmer et d'amplifier leur vote le 5 juin prochain. │
│ La réélection de François MITTERRAND a été rendue possible par les erreurs et les faiblesses du RPR et de l'UDF ainsi que par leur attitude d'exclusion à l'égard du Front National. Ne faites pas confiance à ceux qui ont perdu hier pour gagner demain.                                                                        │
│ Choisissez la seule force d'avenir : le Front National. Faites barrage à l'hégémonie socialiste, à l'arrivée massive de nouveaux immigrés et à l'octroi du droit de vote aux étrangers. Refusez la fatalité du déclin, exprimez vos convictions par…                                                                              │
│ RÉPUBLIQUE FRANÇAISE - Liberté - Égalité - Fraternité - DÉPARTEMENT DE L'AIN                                                                                                                                                                                                                                                      │
│ ÉLECTIONS LÉGISLATIVES DU 5 JUIN 1988 - 1ere CIRCONSCRIPTION                                                                                                                                                                                                                                                                      │
│ CANDIDAT POUR UNE NOUVELLE POLITIQUE A GAUCHE - COMITÉ JUQUIN -                                                                                                                                                                                                                                                                   │
│ Régis PUJOL suppléant : Jean-François MORTEL                                                                                                                                                                                                                                                                                      │
│ J'ai quelques amis en Bresse qui me connaissent bien. Ils vous diront que j'ai 58 ans, 4 enfants, que je suis à gauche, antinucléaire, et que depuis 1980, j'ai galéré de chômage en stages, en passant par le temporaire, l'intérim, et les missions en Afrique.                                                                 │
│ Mais vous, vous vous demandez bien pourquoi un chômeur se pré- sente ?...                                                                                                                                                                                                                                                         │
│ C'est bien simple : Trop longtemps agressé par le chômage, il fallait que je réagisse et que j'agisse, et quand le COMITÉ JUQUIN m'a demandé de le représenter, avec Jean-François MORTEL comme suppléant, j'ai accepté.                                                                                                          │
│ Je voulais ainsi saisir l'occasion de rappeler une fois de plus, qu'une injustice sociale comme le chômage n'est pas une maladie honteuse et dire à chacun de mes camarades sans travail : "Un des nôtres ce…                                                                                                                     │
│ Sciences Po / fonds CEVIPOF                                                                                                                                                                                                                                                                                                       │
│ ELECTIONS LEGISLATIVES DE JUIN 1988 - 1re circonscription de l'Ain                                                                                                                                                                                                                                                                │
│ UNION DU RASSEMBLEMENT ET DU CENTRE R.P.R .- U.D.F.                                                                                                                                                                                                                                                                               │
│ Jacques BOYON                                                                                                                                                                                                                                                                                                                     │
│ Président du Conseil Général de l'Ain Maire de Pont d'Ain Ancien Secrétaire d'Etat à la Défense Chevalier de la Légion d'honneur Père de 7 enfants                                                                                                                                                                                │
│ Suppléant : Paul MORIN                                                                                                                                                                                                                                                                                                            │
│ Vice-Président du Conseil Général de l'Ain Maire-Adjoint honoraire de Bourg en Bresse Commandeur de la Légion d'Honneur                                                                                                                                                                                                           │
│ Cheri Madame, cheio Madenwisell, cher Monsieur,                                                                                                                                                                                                                                                                                   │
│ Avant sa réélection le 8 mai, le Président de la République avait annoncé une "ouverture" de son Gouvernement et de sa majorité. L'ouverture a échoué.                                                                                                                                                                            │
│ Il s'était aussi engagé à ce que son nouveau Gouvernement vienne présenter sa politique devant le Parlement. Au lieu de le faire, il dissout immédiatement l'Assemblée Nationale pour tenter de substituer, à la majorité que vous avez choisie il y a à peine deux ans, une majorité parlementaire à sa convenance.              │
│ Vous devez donc choisir votre député pour…                                                                                                                                                                                                                                                                                        │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [15]:
csv1988.filter((pl.col("contexte-tour")==1) | (pl.col("contexte-tour")==2))

shape: (3_540, 44)
┌────────────────────────────────┬─────────────────────┬─────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───┬────────────────────────────────────────┬───────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────┐
│ id                             ┆ date                ┆ subject                                                         ┆ title                                                                                                                      ┆ … ┆ suppleant-liste                        ┆ suppleant-decorations ┆ transcript                                                                                                                                                                                                                                                                                                                                                ┆ transcript_length │
│ ---                            ┆ ---                 ┆ ---                                                             ┆ ---                                                                                                                        ┆   ┆ ---                                    ┆ ---                   ┆ ---                                                                                                                                                                                                                                                                                                                                                       ┆ ---               │
│ str                            ┆ datetime[μs]        ┆ str                                                             ┆ str                                                                                                                        ┆   ┆ str                                    ┆ str                   ┆ str                                                                                                                                                                                                                                                                                                                                                       ┆ f64               │
╞════════════════════════════════╪═════════════════════╪═════════════════════════════════════════════════════════════════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═══╪════════════════════════════════════════╪═══════════════════════╪═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═══════════════════╡
│ EL174_L_1988_06_001_01_1_PF_01 ┆ 1988-06-05 00:00:00 ┆ France;Assemblée Nationale;Ve République;Élections législatives ┆ Élections législatives de 1988, Ain - 01, circonscription n°01 : profession de foi de Bernard Aulagne au tour 1            ┆ … ┆ Liste d'entente populaire et nationale ┆ non                   ┆ Élections Législatives du 5 Juin 1988 - Département de l'Ain - 1re circonscription                                                                                                                                                                                                                                                                        ┆ 3090.0            │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Sciences Po / fonds CEVIPOF                                                                                                                                                                                                                                                                                                                               ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Maintenant la force d'avenir c'est le Front National                                                                                                                                                                                                                                                                                                      ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Appel aux Français,                                                                                                                                                                                                                                                                                                                                       ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Le 24 Avril, 4.400.000 électrices et électeurs m'ont fait confiance : - pour promouvoir le programme de redressement national, - pour réduire le chômage, l'immigration, l'insécurité, - pour lutter contre le socialisme bureaucratique et fiscaliste. Je leur demande de confirmer et d'amplifier leur vote le 5 juin prochain.                         ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ La réélection de François MITTERRAND a été rendue possible par les erreurs et les faiblesses du RPR et de l'UDF ainsi que par leur attitude d'exclusion à l'égard du Front National. Ne faites pas confiance à ceux qui ont perdu hier pour gagner demain.                                                                                                ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Choisissez la seule force d'avenir : le Front National. Faites barrage à l'hégémonie socialiste, à l'arrivée massive de nouveaux immigrés et à l'octroi du droit de vote aux étrangers. Refusez la fatalité du déclin, exprimez vos convictions par…                                                                                                      ┆                   │
│ EL174_L_1988_06_001_01_1_PF_02 ┆ 1988-06-05 00:00:00 ┆ Élections législatives;Assemblée Nationale;Ve République;France ┆ Élections législatives de 1988, Ain - 01, circonscription n°01 : profession de foi de Régis Pujol au tour 1                ┆ … ┆ Une nouvelle politique à gauche        ┆ non                   ┆ RÉPUBLIQUE FRANÇAISE - Liberté - Égalité - Fraternité - DÉPARTEMENT DE L'AIN                                                                                                                                                                                                                                                                              ┆ 3602.0            │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ ÉLECTIONS LÉGISLATIVES DU 5 JUIN 1988 - 1ere CIRCONSCRIPTION                                                                                                                                                                                                                                                                                              ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ CANDIDAT POUR UNE NOUVELLE POLITIQUE A GAUCHE - COMITÉ JUQUIN -                                                                                                                                                                                                                                                                                           ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Régis PUJOL suppléant : Jean-François MORTEL                                                                                                                                                                                                                                                                                                              ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ J'ai quelques amis en Bresse qui me connaissent bien. Ils vous diront que j'ai 58 ans, 4 enfants, que je suis à gauche, antinucléaire, et que depuis 1980, j'ai galéré de chômage en stages, en passant par le temporaire, l'intérim, et les missions en Afrique.                                                                                         ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Mais vous, vous vous demandez bien pourquoi un chômeur se pré- sente ?...                                                                                                                                                                                                                                                                                 ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ C'est bien simple : Trop longtemps agressé par le chômage, il fallait que je réagisse et que j'agisse, et quand le COMITÉ JUQUIN m'a demandé de le représenter, avec Jean-François MORTEL comme suppléant, j'ai accepté.                                                                                                                                  ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Je voulais ainsi saisir l'occasion de rappeler une fois de plus, qu'une injustice sociale comme le chômage n'est pas une maladie honteuse et dire à chacun de mes camarades sans travail : "Un des nôtres ce…                                                                                                                                             ┆                   │
│ EL174_L_1988_06_001_01_1_PF_03 ┆ 1988-06-05 00:00:00 ┆ Assemblée Nationale;Ve République;Élections législatives;France ┆ Élections législatives de 1988, Ain - 01, circonscription n°01 : profession de foi de Jacques Boyon au tour 1              ┆ … ┆ Union du rassemblement et du centre    ┆ oui                   ┆ Sciences Po / fonds CEVIPOF                                                                                                                                                                                                                                                                                                                               ┆ 5007.0            │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ ELECTIONS LEGISLATIVES DE JUIN 1988 - 1re circonscription de l'Ain                                                                                                                                                                                                                                                                                        ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ UNION DU RASSEMBLEMENT ET DU CENTRE R.P.R .- U.D.F.                                                                                                                                                                                                                                                                                                       ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Jacques BOYON                                                                                                                                                                                                                                                                                                                                             ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Président du Conseil Général de l'Ain Maire de Pont d'Ain Ancien Secrétaire d'Etat à la Défense Chevalier de la Légion d'honneur Père de 7 enfants                                                                                                                                                                                                        ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Suppléant : Paul MORIN                                                                                                                                                                                                                                                                                                                                    ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Vice-Président du Conseil Général de l'Ain Maire-Adjoint honoraire de Bourg en Bresse Commandeur de la Légion d'Honneur                                                                                                                                                                                                                                   ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Cheri Madame, cheio Madenwisell, cher Monsieur,                                                                                                                                                                                                                                                                                                           ┆                   │
│                                ┆                     ┆                                                                 ┆                                                                                                                            ┆   ┆                                        ┆                       ┆ Avant sa réélection le 8 mai, le Président de la République avait annoncé une "ouverture" de son Gouvernement et de sa majorité. L'ouverture a échoué.                                                                                                                                                                                                    ┆                   │